# Generated by Django 6.0.5 on 2026-05-27 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='creada',
            new_name='creado',
        ),
        migrations.AddField(
            model_name='reserva',
            name='cumplida',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='precio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='servicio',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='usuario',
            field=models.CharField(max_length=50),
        ),
    ]
