# Generated by Django 6.0.5 on 2026-05-27 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_rename_creada_reserva_creado_reserva_cumplida_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='creado',
            new_name='creada',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='cumplida',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='servicio',
            field=models.CharField(choices=[('Caballero', 'Caballero'), ('Dama', 'Dama'), ('Barba', 'Barba'), ('Completo', 'Completo')], max_length=100),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
