# Generated by Django 6.0.5 on 2026-05-29 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_rename_creado_reserva_creada_remove_reserva_cumplida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
