# Generated by Django 6.0.5 on 2026-07-08 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_reserva_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='barbero',
            field=models.CharField(default='Sin asignar', max_length=100),
        ),
    ]
